export const FETCH_PHOTO_LOADING="FETCH_PHOTO_LOADING";
export const FETCH_PHOTO_ERROR="FETCH_PHOTO_ERROR";
export const FETCH_PHOTO_SUCCESS="FETCH_PHOTO_SUCCESS";
export const ADD_VALUE="ADD_VALUE";
export const DECREASE_VALUE="DECREASE_VALUE";